sudo: false

language: scala

scala:
  - 2.11.2

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang-format-3.4
    - g++-4.9
    - libtbb-dev
    - libgtest-dev
    - libjemalloc-dev
    - python-pandas

install:
  - pip install conda
  - conda init
  - conda update conda --yes
  - deps='pip numpy pandas requests nose numpydoc sphinx'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH 

script: "source ./tests/testAll.sh"

notifications:
  email:
    - craberger@gmail.com

branches:
  only:
    - master
