sudo: false

language: scala

scala:
  - 2.11.2

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang-format-3.4
    - g++-4.9
    - libtbb-dev
    - libgtest-dev
    - libjemalloc-dev

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
  # Coverage packages are on my binstar channel
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - python setup.py install

script: "source ./tests/testAll.sh"

notifications:
  email:
    - craberger@gmail.com

branches:
  only:
    - master
