sudo: true

language: ruby

services:
  - docker

before_install:
  - docker pull craberger/eh-2.0
  - docker run -d -p 127.0.0.1:80:4567 craberger/eh-2.0 /bin/sh -c "./env.sh"

script: "./test/testAll.sh"

notifications:
  email:
    - craberger@gmail.com

branches:
  only:
    - eh-2.0 
