sudo: false

language: scala

scala:
  - 2.11.2

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - sbt
    - clang-format-3.4
    - g++-4.9
    - libtbb-dev
    - libgtest-dev
    - libjemalloc-dev
    - python-pandas

script: "source ./tests/testAll.sh"

notifications:
  email:
    - craberger@gmail.com

branches:
  only:
    - master
