sudo: false

language: scala

scala:
  - 2.11.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang-format-3.4
    - g++-5
    - gcc-5
    - libtbb-dev
    - libgtest-dev
    - libjemalloc-dev
    - cython

install:
  - conda install -y pandas
  - conda install -y setuptools

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

script: "source ./test/testAll.sh"

notifications:
  email:
    - craberger@gmail.com

branches:
  only:
    - eh-2.0 
